class CnkiSearchError(Exception):
    ...

class BrowserError(CnkiSearchError):
    ...

class ValidationError(CnkiSearchError):
    ...

class CaptchaError(CnkiSearchError):
    ...

class TimeoutError(CnkiSearchError):
    ...

class NoResultsError(CnkiSearchError):
    ...

class ParseError(CnkiSearchError):
    ...

class NavigationStateError(CnkiSearchError):
    ...

class UnsupportedPageError(CnkiSearchError):
    ...

class ExportProcessingError(CnkiSearchError):
    ...
